name: Update packages that depends on cacholote

on:
  workflow_dispatch:
  push:
    tags:
    - "v*"

jobs:
  update-downstream-packages:
    name: Pull request to update packages
    uses: ecmwf-projects/cads-build-farm/.github/workflows/update-downstream-packages.yaml@main
    with:
      package-ref: "CACHOLOTE_REF"
      repositories: |
        ecmwf-projects/cads-adaptors
        ecmwf-projects/cads-broker
        ecmwf-projects/cads-processing-api-service
        ecmwf-projects/cads-worker
    secrets: inherit
